### ISSUE TITLE
Issues with the Docker Run Command...........and solutions

### ISSUE THREAD

**Issue by cdk222** [ParadoxAlarmInterface/pai#102]
## Alarm system
Magellan MG5050 with IP150

## Environment
Proxmox Virtual Env, Debain 10 VM with Docker

## Git branch
Master

## Describe the bug
The Docker run command gave me a few issues. They may be only related to Debian but posting here to help others

## To Reproduce
1) When I ran the Docker command for pai I received a "permission denied" error message relating to -v /opt/pai/log:/var/log/pai section of the run command. I tried to run as sudo and also change the user within the run command to pai but no luck with either.
            - In order to fix this I added the following to the run command.
              --user="$(id -u):$(id -g)"

2) The logs within my paradox container tended to lose time sync with the host after 5 or so hours. After a day or so they tended to drift to about 7 hours difference to the host.
            - I am still testing this but so far after 2 days I am still in sync after adding the following 
               volume creation to the run command.
              -v /etc/timezone:/etc/timezone:ro -v /etc/localtime:/etc/localtime:ro

3) This one is not an issue but more something to note. The MQTT_BIND_ADDRESS in the pai.conf settings required some thought when using Docker. Because Docker creates its own internal network and NAT, I was unable to use the default loopback (127.0.0.1) for the BIND. I was also not able to use my host IP. Instead I had the use the Paradox container IP address (172.x.x.x), that the docker creates for itself, as the BIND_ADDRESS. Issue with this is that it is not static and will change on a reboot of the host. I am currently playing with the docker network settings to have this statically assigned. If anyone has already come across this please add a comment.

**Comment by yozik04** [comment]
Hi. Can you create a pull request fixing these?

**Comment by cdk222** [comment]
I will have a look into how to merge these changes with the Dockerfile, rather than having a lengthy Docker run command (which is what i used). It may take me a few days as im still learning Docker, then will submit as a Pull Request

**Comment by yozik04** [comment]
If you can, please create a docker-compose.yaml file example and add docker run command example to README :)

Me and João do not use docker for PAI so we are a bit lazy to fix it.

**Comment by cdk222** [comment]
Will figure out the static IP for the network side and then add

**Comment by yozik04** [comment]
Why do you need a static IP?

**Comment by cdk222** [comment]
If the VM or docker host are rebooted then the IP allocation for docker containers is random. The containers use their own internal 172.x.x.x network which is then NAT'd (I assume) out to the host VM network. 7 times out of 10 it gets the same IP but its not guaranteed....especially if you have a lot of containers. I cant set the MQTT_BIND_ADDRESS in pai.conf to the host IP or use localhost as it doesn't appear to work when establishing the MQTT interface

**Comment by yozik04** [comment]
Doesn’t 0.0.0.0 work?

**Comment by cdk222** [comment]
lol - didnt try that. It worked a treat. Some times you get so caught up that you miss the simple stuff

**Comment by yozik04** [comment]
@jpbarraca Why we have default `MQTT_BIND_ADDRESS = '127.0.0.1'`. Can I change to `'0.0.0.0'` as default?

**Comment by yozik04** [comment]
or `""`, which is PahoMqtt default?

**Comment by jpbarraca** [comment]
Because 127.0.0.1 is more restrictive and will protect incautious users. I agree that it presents issues with many scenarios. Maybe we can just include a better description in this setting.

**Comment by yozik04** [comment]
people do not read =)

**Comment by ivmarkov** [comment]
My take on issues (1) and (2) from above after ~ two days of banging my head against the docker command line and docker principles.

(1) - The suggested "workaround" of using the docker "--user" option is in fact the correct solution (assuming that user namespaces are not enabled in the docker daemon, and they are not, by default). I suggest we update the wiki to reflect that. There is a long, boring explanation below.

(2) - Adding the volume mounts `-v /etc/timezone:/etc/timezone:ro -v /etc/localtime:/etc/localtime:ro` to the `docker run` command line is also a very good idea, and I suggest we update the wiki with this as well. However this just makes sure that the container will use the same timezone as the timezone of the host. I don't think however that it can fix any clock "drifting", as the clock should not drift in the first place, due to the container and the host sharing the same kernel. There are reported bugs on the internet related to container clock drifting, but they seem to be caused not by the concrete pai image, but by the docker daemon itself - when e.g. it runs on Mac/Windows, where an additional VM is used for the Linux host, and this VM - in turn - drifts its clock on laptop suspend/resume from the actual host clock. Fixing this is beyond our scope.

Finally, none of these additions can be "fixed" by updating the Dockerfile. Volume mounts cannot be expressed in the Dockerfile by design, as they are always host specific. Ditto for the "--user" option.

In fact, I would do exactly the opposite - If there's anything we should fix in the Dockerfile, it would be the removal of the pai.conf file from the container image, as it contains host/use-case specific configuration and as such should not be part of the image.

============

Long explanation of the 'permission denied' problem observed in (1):

It all stems from the fact how docker maps users and groups internal to the container to ones external to the container (in the host system) when it needs to read/write from/to host files and directories.

The rule is super-simple: the host and the container *share* the user and group IDs (not names, mind you, their numeric IDs!), as they are all governed by a single kernel. So the internal container user "pai" which happens to have  UID = 100 is automatically mapped to this user in the host system, which happens to also have UID = 100 in the host system. If a user with UID = 100 does not exist in the host system, you get a permission denied exception. If a user with UID = 100 does exist, but it does not have appropriate permissions to e.g.  "/opt/pai/log", you'll also get a permission denied exception. So unless you provide the --user option, it all works by mere coincidence.

The above explains e.g. why it does not work on a stock raspbian system. 
First, the pai user inside the docker image has an ID of 100. You can check this by executing 
`docker run -it batvanyovanistia/pai id`
(batvanyovanistia/pai is a raspberry armv7 image I built for testing, available in Docker Hub.)

The above command should print something like:
`uid=100(pai) gid=1000(pai) groups=1000(pai)`

Now, on a clean raspbian system, if you do `cat /etc/passwd | grep 100`, you would either see no output at all, or
`systemd-timesync:x:100:102:systemd Time Synchronization,,,:/run/systemd:/usr/sbin/nologin`.

In other words, it tries to use a user which does not exist, or the systemd-timesync user when writing in /opt/pai/log!

Rather than doing any equilibristics with the Docker file to fix this, the correct way seems to be to use the docker `--user` option. When running the container, this option overrides the default 'pai' user specified in the Docker image with the user whose name or numeric UID is provided on the docker command line. Note also that using `--user pai` does not work, simply because when specifying users by name, docker consults the /etc/passwd file which is *inside* the container, not the one in the host, so this option - in fact - does not change anything!

Specifying a numeric user UID will work, as long as this UID exists on the host system. This is why `"--user=$(id -u)"` works - because you are overriding the internal pai user with your current host user.

**Comment by yozik04** [comment]
Thank you for the contribution.
I've added `--user` and timezone stuff to the docker command in the wiki.

Will remove configuration file from the image as well.

I see you are doing some good progress in travis configuration in your repo. Let us know if it works for building multi-arch =)
